# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/py2html',
                'doc_host': 'https://mylearnit.github.io',
                'git_url': 'https://github.com/mylearnit/py2html',
                'lib_path': 'py2html'},
  'syms': {'py2html.core': {'py2html.core.say_hello': ('core.html#say_hello', 'py2html/core.py')}}}
